### ISSUE TITLE
Fly anywhere by unclaiming chunk

### ISSUE THREAD

**Issue by JustinDevB** [TownyAdvanced/TownyFlight#53] opened 2021-06-23 18:31 UTC
### What steps can be done to repeat the issue on a test server?
1. Give yourself fly in a claim with /tfly
2. do /t unclaim to unclaim the chunk
3. You can now fly anywhere without it being removed unless you re-enter the claim

### What is supposed to happen instead?
1. Not able to fly outside of your own claims

### Versions/Files

Towny Version (use '/towny v' in game) : 0.97.0.0
TownyFlight Version : 1.6.7
Link to pastebin.com with full server startup from the latest.log : https://pastebin.com/Q46H63kP
Link to pastebin.com with TownyFlight config.yml : https://pastebin.com/8iHVU5st

**Comment by LlmDl** [comment] 2021-06-23 19:14
This is something I cannot reproduce on my test server and seems to only affect a small number of servers. Duplicate of #48 #46 #45 #44 #41. If you want, ask me for a dev build in the discord, which I keep giving to people with the issue but they never tell me if its fixed it or not.

**Closed by LlmDl** 2021-06-23 19:14 UTC
